name: tasmik
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.8
  flutter_markdown: ^0.6.10+4
  
  url_launcher: ^6.1.5
  flutter_launcher_icons: ^0.10.0

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#E9F1F4"
  image: images/tasmiklogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  web:
    generate: true
    image_path: "images/icon.png"
    background_color: "#E9F1F4"
    theme_color: "#E9F1F4"
  windows:
    generate: true
    image_path: "images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family : isepMisbah
      fonts :
        - asset: fonts/IsepMisbah.ttf
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
